### ISSUE TITLE
get_parameter_vector doesn't return mean

### ISSUE THREAD

**Issue by saigrain** [dfm/celerite#105] opened 2017-05-11 15:48 UTC
If I set up a GP with fit_mean=True, the mean is included in the output of get_parameter_names and get_parameter_dict, but not get_parameter_vector

**Comment by dfm** [comment] 2017-05-11 16:42
What version of celerite are you using and how did you install? Can you include a code snippet that fails? I can't reproduce this issue over here.

**Comment by dfm** [comment] 2017-05-18 15:47
@saigrain: any update on this?

**Comment by saigrain** [comment] 2017-05-18 18:08
Hi Dan

Will send you snippet tomorrow I hope - currently stuck at home looking
after chicken poxy babies.

Suzanne

**Comment by ericagol** [comment] 2017-05-18 20:19
@saigrain You have twins?  I have a twin brother as well.  Sorry to hear they're ill.

**Comment by saigrain** [comment] 2017-05-19 15:20
@ericagol not twins but a 2 year old and a 7 month old. I'm sure the
toddler would hate it if he heard me call him a baby... He's recovered now
but the actual baby is just beginning. Neither has had it too bad so far
but they still have to be out of nursery for a long time.

@danfm can't seem to reproduce the problem now I've upgraded to a newer
version of celerite. I'll let you know if I ever encounter it again.

**Comment by dfm** [comment] 2017-05-19 22:06
I'm sorry to hear bout the kids. I hope they recover quickly!

I'm going to close this issue for now, but please feel free to re-open it if you run into this again.

**Closed by dfm** 2017-05-19 22:06 UTC
Labels: question
